a = Scene.createSprite("arcahv-srt", "arcahv-srt.png")
a.setLayerName("Background")
a.setTranslation(0,271,0)
a.setLayerOrder(1)
a = Scene.createSprite("arcahv-debris", "arcahv-debris.png")
a.setLayerName("Background")
a.setLayerOrder(2)
a.setTranslation(0,150,0)
Scene.createSprite("antilock", "antilock.png")
